### ISSUE TITLE
Save flagged sample report and start new flagged sample report 

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/QWToolbox#16]
Need to add option to save a flagged sample report and then clear it and start a new one

**Comment by mcanova-usgs** [comment]
There is also some quirky behaviors where the Flagged sample report seems to be a one session deal. 
You can type into Notes but not modify after saving.
You can type what you want into Rerun.submitted but it only seems to store NA.
If possible the parameter code flagged should be indicated too in the Flagged sample report.

**Comment by tmills-usgs** [comment]
I will address these issues when I can. The flagged sample report was slated for a later release but I managed to get it into this version. Little testing has been done on this feature so far. 
Thanks for the report Mike!

**Comment by tmills-usgs** [comment]
All instances of flag function have now been removed until the function can be improved. To much risk of misinterpreting data.
