### ISSUE TITLE
Title Format on Matrix Plot

### ISSUE THREAD

**Issue by mcanova-usgs** [USGS-R/QWToolbox#22]
Small picky thing but the title on the matrix plot overwrites itself. If it is a multi-site matrix plot it should be labeled Multisite.

![image](https://cloud.githubusercontent.com/assets/4225891/5652383/b59bc60a-9675-11e4-9408-7c5c557e718b.png)

**Comment by tmills-usgs** [comment]
Thanks I overlooked that one, will be an easy fix.

**Comment by tmills-usgs** [comment]
Fixed but not pushed to master

**Comment by tmills-usgs** [comment]
pushed to master
