### ISSUE TITLE
Need to distinguish censored and estimated values from other values.

### ISSUE THREAD

**Issue by cjhoard** [USGS-R/QWToolbox#32]
I was wondering if there was some way to either change the symbol or change the color for a value that is censored or estimated.  It looks like NWISPullR is reading in "Sample" for the remark code instead of the actual remark code of "<", or "E".  So on the plot the Qualifier code is just listed as Sample.  I was not sure if this is a bug or if this is functionality you would need to add.

**Comment by tmills-usgs** [comment]
This is a bug in hte new version. I changes NWISPullR and this cropped up. It used to distinguish, I will fix. Thanks

**Comment by tmills-usgs** [comment]
Fixed and pushed to master. Re-install. Sorry about that
