### ISSUE TITLE
Export plot function

### ISSUE THREAD

**Issue by usgsmlclark** [USGS-R/QWToolbox#36]
The QWToolbox Export Plot function brings up a window that says "Select site ID file..." Save/Close. This is confusing to the user. The Plot Window itself has a File button, which includes a "Save as" option. This seems to be a better way to save a plot, so you might consider just removing the "Export Plot" option from the QWToolbox screens.

**Comment by tmills-usgs** [comment]
Sorry, this is an old feature that has been deprecated. I will remove from the GUI. Plot can now be exported from the plot window menu.
