### ISSUE TITLE
Timeseries plotting does not seem to be include the last sample for selected dates.

### ISSUE THREAD

**Issue by usgsmlclark** [USGS-R/QWToolbox#38]
The time series plot seems to cut off and not include the last sample in a data set. The "Begin Date" and "End date" feature correctly indicates the range the of sample dates, but the time series plot itself seems to always be missing the final data point.

**Comment by tmills-usgs** [comment]
This is a problem with converting between timezones. I will address this today

**Comment by tmills-usgs** [comment]
Fixed but not pushed to master
