### ISSUE TITLE
Data import from file with sites and parameters in csv format does not work 

### ISSUE THREAD

**Issue by usgsmlclark** [USGS-R/QWToolbox#39]
I created multiple site IDs with a comma separator in one file and multiple parameters with a comma separator in a second file. Then I used the "from file" option with a date range to import the data. The Plotting windows indicate that only the last site and the last parameter were imported.

**Comment by usgsmlclark** [comment]
After more testing, I did get this to work. A file created in Unix with CSV format did not work, but a CSV file from Excel did work. R must want the Microsoft-embedded characters. This can be explained in the user documentation to create the file with Excel.

**Comment by tmills-usgs** [comment]
This is probably a formatting issue. It does not read special characters from Excel. Rather, the csv files needed for this are delimited by rows and columns. Each new entry must be on a different row, and the different columns are delimited by commas.
