### ISSUE TITLE
Data import from "Favorite" list does not seem to work.

### ISSUE THREAD

**Issue by usgsmlclark** [USGS-R/QWToolbox#40]
I cannot get the data import from the favorite list to work. I am getting an NA on the last line of my favorites on the screen, which might be the problem, but I can't seem to delete it. I am receiving the error:
Error in dim(ordered) <- ns : 
  dims [product 1] do not match the length of object [0]

**Comment by tmills-usgs** [comment]
This error indicates no data was pulled, which is probably because no sites were selected. The NA will not matter. Did you actually select sites in your favorite list? If you do not select one or multiple sites from the list it will not pull any data.

**Comment by usgsmlclark** [comment]
This is OK. User error. Still getting the hang of having to highlight things....sorry.
