### ISSUE TITLE
Latest version is not working on the "calculating charge balance" step

### ISSUE THREAD

**Issue by usgsmlclark** [USGS-R/QWToolbox#41]
In the 1/22/15 version of qwtoolbox, the import process hangs on the charge balance computation. The following error is received:
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'Data/ion_bal_mills.csv': No such file or directory

**Comment by tmills-usgs** [comment]
ion balance data was not saved to the package when I reloaded. It will be fixed today

**Comment by tmills-usgs** [comment]
Should be fixed now

**Comment by usgsmlclark** [comment]
Tried to do the new install and getting an error:
Error: cannot allocate memory block of size 2.3 Gb

**Comment by tmills-usgs** [comment]
Try emptying your environment and re-installing. Click "clear" in the top right pain of R studio to clear the environment. I just installed the latest version on two different laptops with no issue. Let me know if this continue to be a problem.

**Comment by mcanova-usgs** [comment]
I just reinstalled and ran into the same problem as Melanie. 
Bad news: my environment was already cleared when I ran into this.
Good news: a re-install seemed to fix it!

**Comment by tmills-usgs** [comment]
When you say re-install for good news, was that a reinstall of R or qwtoolbox fixed it?

**Comment by mcanova-usgs** [comment]
I meant a reinstall of qwtoolbox.

**Comment by tmills-usgs** [comment]
OK, I think this breaks when trying to install QWToolbox while the QWToolbox package is loaded. When the installer breaks the first time, the old QWToolbox package is unloaded. Then, when you try again it installs without the old version loaded, and works. I will think about what is happening there.
