### ISSUE TITLE
Ion Bal Calculations Fail due to Missing File

### ISSUE THREAD

**Issue by mcanova-usgs** [USGS-R/QWToolbox#42]
Just downloaded the latest version of QWToolbox and while importing data the "PLEASE WAIT, CALCULATING CHARGE BALANCE" widow appears to hang up.
Here are all of the error messages from the console window.

=======================================================================
> qwtoolbox(dlserver.name = "NWISTX", env.db.num = "01", qa.db.num = "02")
Loading required package: gWidgetsRGtk2
Loading required package: gWidgets

(rsession.exe:3868): Gtk-WARNING **: Could not find the icon 'gtk-file'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases
Read 6 items
Aggregation function missing: defaulting to length
Aggregation function missing: defaulting to length
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'Data/ion_bal_mills.csv': No such file or directory
=======================================================================

The last line appears to be the problem.
The other plot types seem to available. I like that robustness.

**Comment by tmills-usgs** [comment]
I did not update the ion balance data in the package on the latest load. End of the day Friday afternoon goof....
It should be fixed now
