### ISSUE TITLE
Enhancement Request to Highlight Results of Particular Sample

### ISSUE THREAD

**Issue by mcanova-usgs** [USGS-R/QWToolbox#44]
Usually when reviewing data I am reviewing a particular sample. I would like to see where the results of the sample are on the various plots so that I can quickly spot outliers.
One idea would be to have a spot on the Data import tab to indicate Record Number being reviewed.

**Comment by tmills-usgs** [comment]
Maybe a different symbol shape for the record of interest? I could also make it a little bigger to stand out more. At the top of hte plotting pain near the "New threshold" selection, I can put in another box for typing in the record number being reviewed

**Comment by tmills-usgs** [comment]
I have added this enhancement. You may now select a particular record from a sortable list off all records in data. The selected record will be highlighted on all plots with a large translucent symbol on top of the original symbol. Like halo
