### ISSUE TITLE
Enhancement Request Additional Method to Group Parameters

### ISSUE THREAD

**Issue by mcanova-usgs** [USGS-R/QWToolbox#45]
Under the plotting tab it is a really nice feature to be able to sort the pcodes by name and sequence group code. Another field that may be useful is the parameter sequence number, that is also what we call Publication Order. This would put all your majors, metals, nutrients, and so on into nice groups.

It is stored in the PARM table.

SELECT NWISTX_PARM.PARM_SEQ_NU
FROM NWISTX_PARM;

**Comment by tmills-usgs** [comment]
Working on this now, I should have it updated in an hour or two

**Comment by tmills-usgs** [comment]
Added PARM_SEQ_NU to sort list in all plots. Has not been been pushed to master yet,
