### ISSUE TITLE
Enhancement to Add analysis of Replicate Samples

### ISSUE THREAD

**Issue by mcanova-usgs** [USGS-R/QWToolbox#48]
In a future version it may be nice to have a way to analyze replicates. Replicate analysis is addressed here:
http://phoenix.cr.usgs.gov/www/replicatecalculator.html

Since I am not able to attach a file the code for rep I pasted it below. 

#######################################################
#!/bin/bash

# Yet another simple tool that does one thing well
# 
# This program pulls raw data for two specified records and joins them
# based on parameter code, does some math and puts it in an Excel file. 
# 
# Cool or what!
#
# Copy this file to where you want to use it. This is where the output will go.
# 
# Make the file executable by using the following command
# chmod u+x rep
# 
# You will need to change nwistx to your two letter state code. nwisXX
#
# Run the program like this
# rep record_no db_no record_no db_no
# 
# For example if your environmental database is 01 and the qc is 02
# rep 01000159 01 01000028 02
#
# The output for the example above would be 
# rep_env.01000159.01_qc.01000028.02.xlsx
#
# Open the file in Excel 
# Recording a macro to automate some logical comparisons is highly recommended.
# For example:
# Is the sum of the reporting limits greater than the difference of the results?
# Is the result greater than 10 times the reporting limit? If true then use the rsd 
# column if false use the stddev column.
#
# rpd = Relative percent difference
# pd = Percent difference
# pcntenv = Percent of environmental
# stnddev = Standard deviation
# rsd = Relative standard deviation
# 
# The percentenv column may be a handy way to look at the impact of blank contamination
# on the environmental sample.
#
# NOTE: This will only join two results if the parameter codes match and neither of the 
# results are null or zero.
#
# Michael Canova 20110921
# 
tsql nwistx -Gnwis_select -rdb "SELECT qw_sample_${2}.record_no, qw_sample_${4}.record_no, qw_sample_${2}.project_cd, qw_sample_${4}.project_cd, qw_sample_${2}.sample_cn, qw_sample_${4}.sample_cn, qw_sample_${2}.samp_type_cd, qw_sample_${4}.samp_type_cd,parm.parm_seq_grp_cd, parm.parm_nm, qw_result_${2}.parm_cd, qw_result_${2}.meth_cd, qw_result_${2}.rpt_lev_va, qw_result_${4}.meth_cd, qw_result_${4}.rpt_lev_va, qw_result_${2}.remark_cd, qw_result_${2}.result_va, qw_result_${4}.remark_cd, qw_result_${4}.result_va, ((qw_result_${2}.result_va-qw_result_${4}.result_va)/((qw_result_${2}.result_va+qw_result_${4}.result_va)/2))*100 AS RPD,  ((qw_result_${2}.result_va-qw_result_${4}.result_va)/((qw_result_${2}.result_va+qw_result_${4}.result_va)))*100 AS PD, (qw_result_${4}.result_va/qw_result_${2}.result_va)*100 AS PcntEnv, ((qw_result_${2}.result_va + qw_result_${4}.result_va)/2) AS Average, Sqrt((((qw_result_${2}.result_va-((qw_result_${2}.result_va + qw_result_${4}.result_va)/2))*(qw_result_${2}.result_va-((qw_result_${2}.result_va + qw_result_${4}.result_va)/2)))+((qw_result_${4}.result_va-((qw_result_${2}.result_va + qw_result_${4}.result_va)/2))*(qw_result_${4}.result_va-((qw_result_${2}.result_va + qw_result_${4}.result_va)/2)))/1)) AS StndDev, 100*((Sqrt((((qw_result_${2}.result_va-((qw_result_${2}.result_va + qw_result_${4}.result_va)/2))*(qw_result_${2}.result_va-((qw_result_${2}.result_va + qw_result_${4}.result_va)/2)))+((qw_result_${4}.result_va-((qw_result_${2}.result_va + qw_result_${4}.result_va)/2))*(qw_result_${4}.result_va-((qw_result_${2}.result_va + qw_result_${4}.result_va)/2)))/1)))/((qw_result_${2}.result_va+qw_result_${4}.result_va)/2)) AS RSD
FROM ((parm INNER JOIN (qw_result_${2} INNER JOIN qw_result_${4} ON qw_result_${2}.parm_cd = qw_result_${4}.parm_cd) ON (parm.parm_cd = qw_result_${2}.parm_cd) AND (parm.parm_cd = qw_result_${4}.parm_cd)) INNER JOIN qw_sample_${4} ON qw_result_${4}.record_no = qw_sample_${4}.record_no) INNER JOIN qw_sample_${2} ON qw_result_${2}.record_no = qw_sample_${2}.record_no
WHERE (((qw_sample_${2}.record_no)= '${1}') AND ((qw_sample_${4}.record_no)= '${3}') AND ((qw_result_${2}.result_va) Is Not Null And (qw_result_${2}.result_va)<>0) AND ((qw_result_${4}.result_va) Is Not Null And (qw_result_${4}.result_va)<>0))" > rep_env.${1}_qc.${3}.rdb;
#
# Comment out the following line of code if you do not prefer Excel.
#
 rdb2excel rep_env.${1}_qc.${3}.rdb rep_env.${1}.${2}_qc.${3}.${4}.xlsx ; sleep 1 ;
#
# Comment out the following line of code if you would like to keep the rdb file.
#
# rm rep_env.${1}_qc.${3}.rdb ; echo "Output saved as rep_env.${1}.${2}_qc.${3}.${4}.xlsx"

**Comment by tmills-usgs** [comment]
Thanks mike! I have already included a basic rep analysis table that pairs environmental samples with its rep and calculates a relative percent difference. If the RPD is >10% and the difference is > LRL it gets flagged. I will look into some of this other code soon

**Comment by tmills-usgs** [comment]
Added but need to make flexible so users can define thresholds. Closing for now and a new issue can be created later with input from users
