### ISSUE TITLE
Charge balance function failure

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/QWToolbox#49]
Fails sometimes, possibly due to some records missing ALL charge balance data, including pH

**Comment by tmills-usgs** [comment]
May have been fixed, needs additional testing

**Comment by usgsmlclark** [comment]
Charge balance 'hanging' on data import. Received the following error in console:
Error: replacement has 2 rows, data has 13

**Comment by tmills-usgs** [comment]
Is this from the WEB or internal data pull?

**Comment by usgsmlclark** [comment]
This was an internal data import.

**Comment by usgsmlclark** [comment]
Charge balance plotting as "incomplete" for site that has complete data.

**Comment by tmills-usgs** [comment]
The data you sent me has no values for NO2/NO3 and hence is not a complete charge balance dataset

**Comment by usgsmlclark** [comment]
NO2/NO3 is not considered a mandatory constituent for a charge balance in QWDATA (contribution is insignificant for most environmental SW/GW). Use it if it is there, proceed if it is not. Too many sites will fail this criteria--can you remove it as a requirement?

**Comment by tmills-usgs** [comment]
I was having this discussion with a person here in my office and we opted to leave it in. I did not know it was not included in the QWData requirement. I will remove this as a mandatory constituent for "complete chem"

**Comment by usgsmlclark** [comment]
Still having trouble importing data for a site where some historical data are missing for charge balance, but last 10+ years of data has major ions. A new error that will maybe help trouble shoot:
Error in eval(expr, envir, enclos) : object 'perc.diff' not found

**Comment by tmills-usgs** [comment]
NO2/NO3 removed as criteria for complete charge
