### ISSUE TITLE
NWISWeb data load failed

### ISSUE THREAD

**Issue by usgsmlclark** [USGS-R/QWToolbox#51]
I tried to load all data for site 06317000 and received the following errors:
Aggregation function missing: defaulting to length
Error in seq.int(0, to0 - from, by) : 'to' cannot be NA, NaN or infinite
In addition: Warning messages:
1: In readNWISpCode(parameterCd) :
  The following pCodes seem mistyped, and no information was returned: 96202,96209,96218,96230,96243,96252,96387,96706,96731,96765,96777,96791,96812,98131,98158,98165,98182
2: In readNWISpCode(parameterCd) :
  The following pCodes seem mistyped, and no information was returned: 96202,96209,96218,96230,96243,96252,96387,96706,96731,96765,96777,96791,96812,98131,98158,98165,98182

**Comment by tmills-usgs** [comment]
This has popped up before with me, I had hoped it was just that site. I will disable this function until the issue with the supporting function (dataRetrieval) is resolved. This one is out of my hands

**Comment by tmills-usgs** [comment]
Removed function until further troubleshooting. Pushed to master
