### ISSUE TITLE
Errors received with Site mapper feature

### ISSUE THREAD

**Issue by usgsmlclark** [USGS-R/QWToolbox#66]
I played around with the Site mapper feature for a while with little success. I would suggest removing this tab until feature works better.  Some of errors received follow:
Error in aggregate.data.frame(mf[1L], mf[-1L], FUN = FUN, ...) : 
  no rows to aggregate
In addition: Warning messages:
1: Removed 1 rows containing missing values (geom_point). 
2: Removed 1 rows containing missing values (geom_point). 
3: Removed 1 rows containing missing values (geom_point). 
Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=44.649982,-106.127528&zoom=12&size=%20640x640&scale=%202&maptype=terrain&sensor=false
Google Maps API Terms of Service : http://developers.google.com/maps/terms
Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=43.083168,-107.788276&zoom=12&size=%20640x640&scale=%202&maptype=terrain&sensor=false
Google Maps API Terms of Service : http://developers.google.com/maps/terms
Error: 'x' and 'units' must have length > 0
In addition: Warning messages:
1: Removed 2 rows containing missing values (geom_point). 
2: Removed 2 rows containing missing values (geom_text). 
Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=43.679329,-107.219784&zoom=12&size=%20640x640&scale=%202&maptype=terrain&sensor=false
Google Maps API Terms of Service : http://developers.google.com/maps/terms
Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=43.679329,-107.219784&zoom=12&size=%20640x640&scale=%202&maptype=terrain&sensor=false
Google Maps API Terms of Service : http://developers.google.com/maps/terms
Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=43.679329,-107.219784&zoom=12&size=%20640x640&scale=%202&maptype=terrain&sensor=false
Google Maps API Terms of Service : http://developers.google.com/maps/terms
Error: 'x' and 'units' must have length > 0
In addition: Warning messages:
1: Removed 3 rows containing missing values (geom_point). 
2: Removed 3 rows containing missing values (geom_point). 
3: Removed 3 rows containing missing values (geom_point). 
4: Removed 3 rows containing missing values (geom_text).

**Comment by tmills-usgs** [comment]
These are messages indicating there were no data to be mapped

**Comment by usgsmlclark** [comment]
I definitely have data. I have sites highlighted. Here is another error:

(rsession.exe:5792): Gtk-WARNING **: Could not find the icon 'gtk-file'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases
Read 2 items
Read 3 items
Error in aggregate.data.frame(mf[1L], mf[-1L], FUN = FUN, ...) : 
  no rows to aggregate
Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=44.760817,-106.105165&zoom=12&size=%20640x640&scale=%202&maptype=terrain&sensor=false
Google Maps API Terms of Service : http://developers.google.com/maps/terms

**Comment by tmills-usgs** [comment]
does your data have only 1 sample? This could be causing an error, which I can fix. If it has multiple samples and there are data for the particular pcode, then I will have to pull the data myself to see what is causing the problem.

**Comment by usgsmlclark** [comment]
I am selecting all the SC data for 06317000 and 06324000. You can see on NWISWeb that there is lots of data for both sites.

**Comment by mcanova-usgs** [comment]
I am receiving the same error. I can get it to work for some sites. I do not know what is different between the data sets though.

Here I am trying to plot 4 sites.

Read 4 items
Error in aggregate.data.frame(mf[1L], mf[-1L], FUN = FUN, ...) : 
  no rows to aggregate

It may require a separate PR but remarked results do not show on the map.

**Comment by tmills-usgs** [comment]
The remark code could be the issue. The site mapper currently only plots remark codes of "Sample". i.e. no < or Es. So if a particular site or set of sites has all < or E values it will not have any data to plot.

I am removing this tab until further testing since it is causing issues

**Comment by usgsmlclark** [comment]
I don't think it is remark code. I was trying to plot specific conductance, which is rarely ever remarked.
