### ISSUE TITLE
Enhancement request for parameter information to include "units"

### ISSUE THREAD

**Issue by usgsmlclark** [USGS-R/QWToolbox#67]
The plots and parameter listing do not include information about the units. Units could be added to the parmater listing on the Plotting screen with: parm_cd, parm_nm, parm_seq_grp_cd, parm_seq_nu. It would be nice to have on the plot as well, but might be more difficult to do. Parameter units are found in the parm_unt_tx attribute and the parm_ds attribute.

**Comment by tmills-usgs** [comment]
Units are on the plot in the y axis label. I will add them to the parameter listing
