### ISSUE TITLE
Time-series date scale and slide bar for changing time period are inconsistent with hydrograph

### ISSUE THREAD

**Issue by usgsmlclark** [USGS-R/QWToolbox#70]
I'm noticing that the time-scale for the hydrograph and chemical constituent are inconsistent. For example, I have discharge 00060 that starts in 1946 and selenium that starts in 1976. The date scale goes to the 1976 selenium dates, but the hydrograph is plotting data back to 1946, even though the selenium date range is what shows for both Se and Q. Using the slide bar to change the date does not go to the date range specified. The Q changes to that date range, but the Se plots for a date range indicated in the data, not indicated by the slide bar. So again, the date range is not consistent with the hydrograph that plots.

**Comment by tmills-usgs** [comment]
Should be fixed now. Reinstall from my personal repository using the following code. I put labels on the hydrograph plot in this version so you can see if it is matching up. If this fixed the issue I will remove those extra labels and push the change to the master repository.
