### ISSUE TITLE
Issues with Flag Sample

### ISSUE THREAD

**Issue by mcanova-usgs** [USGS-R/QWToolbox#75]
I am using the tmills-usgs dev version of QWToolbox for this issue.
The record highlighter is really cool! 
Flag sample does not work in the Timeseries and Parameter-parameter plots.

Error from Timeseries plot
Error in subset(qw.data$PlotTable, SITE_NO %in% (its.site.selection) &  : 
  object 'qw.data' not found
In addition: Warning messages:
1: Removed 1 rows containing missing values (geom_point). 
2: Removed 1 rows containing missing values (geom_point). 

Error from Parm-parm plot
Error in match(x, table, nomatch = 0L) : 
  argument "highlightrecords" is missing, with no default
In addition: Warning messages:
1: Removed 4 rows containing missing values (geom_point). 
2: Removed 1 rows containing missing values (geom_point).

**Comment by tmills-usgs** [comment]
I believe I fixed the second issue yesterday afternoon. It should be updated on the master USGS-R/QWToolbox repository. 

I will look at the flagger isssue. I might disable that for now since we have the highlight function in place.

**Comment by tmills-usgs** [comment]
All instances of flag function have now been removed until the function can be improved. To much risk of misinterpreting data.
