### ISSUE TITLE
Charge Balance Error

### ISSUE THREAD

**Issue by mcanova-usgs** [USGS-R/QWToolbox#79]
I was pulling other organic data for 08155500. So, only parameter 39516 was being pulled. That broke the charge balance calculation. Error message pasted below.

> qwtoolbox(dlserver.name = "NWISTX", env.db.num = "01", qa.db.num = "02")
Error in value[[3L]](cond) : 
  Error in if (nrow(.guiEnv$chargebalance.table) > 0) {: argument is of length zero
Fatal error with charge balance. Please report this whole message on the github issues page

**Comment by tmills-usgs** [comment]
Thanks Mike. Did the rest of hte program continue to load? The most recent version, which you are using, has some initial attempts at error handling. So, hopefully the program continued despite the charge balance failure. Note the english error message at the bottom, this is my first attempts at making it spit out general errors that folks will understand.

**Comment by mcanova-usgs** [comment]
The tabs stopped forming once I hit the error. Everything else seemed
functional but I did not continue to test.

**Comment by tmills-usgs** [comment]
Hey Mike, I am not sure I would classify this as a bug. If there is not data for the charge balance then it won't calculate it. As long as the rest of the program ran then its all good. I will change that error message to include a message to tell users to check that data are sufficient for a charge balance calc.
Thoughts?

**Comment by mcanova-usgs** [comment]
That is a good idea.
The primary reason I sent it to you was that the error message said to.

**Comment by tmills-usgs** [comment]
cool, thanks for posting. I will add it to the laundry list
