### ISSUE TITLE
"Clear" does not work for 'cannot allocate memory block' error

### ISSUE THREAD

**Issue by usgsmlclark** [USGS-R/QWToolbox#83]
I seem to get the 'Error: cannot allocate memory block of size 2.8 Gb' very frequently. Was the new instruction "detach("package:QWToolbox", unload=TRUE)" supposed to fix the problem? If so, it did not work. 

The only way I can get things to work is to completely exit RStudio and start over.

**Comment by usgsmlclark** [comment]
I created a new project space and so far I have not had the memory block error happen in the new area. I have installed the software several several times to try to trigger the error, but no problems have been experienced. Fixed?

**Comment by tmills-usgs** [comment]
This one is kind of a mystery to me at this point. I will have to wait until its a consistant problem again before I can investigate. Glad its working now though. I am working on a new bug reporting feature that will export everything I need to run the user's QWToolbox exactly as they did when they left off.
