### ISSUE TITLE
Ion vs conductance not working

### ISSUE THREAD

**Issue by usgsmlclark** [USGS-R/QWToolbox#90]
I have gone through the plotting options in the latest version (2/11/14) of the software. Everything seems to be working except the Ion vs Conductance plot. The following error is received:
Error: Aesthetics must either be length one, or the same length as the dataProblems:RESULT_VA, sum_an
Error: Aesthetics must either be length one, or the same length as the dataProblems:RESULT_VA, sum_cat

**Comment by tmills-usgs** [comment]
Thanks Melanie, can you generate a bug report using the bug report option in the gui and email it to me? This plot is not breaking with my data

**Comment by tmills-usgs** [comment]
Fixed but not pushed to master

**Comment by tmills-usgs** [comment]
pushed to master
