### ISSUE TITLE
odbc setup

### ISSUE THREAD

**Issue by cvmiller565** [USGS-R/QWToolbox#98]
I can't get my odbc set up (Step 1 on your instructions.
When I type in your command:

:: Set up DSN for access to NWIS database
odbcconf.exe /A {configsysdsn "Oracle in OraClient11g_home1" "DSN=NWISMD|SERVERNAME=NWISMD|DATABASE=nwismd"}

 I get this error message. My SA tried to do it too and got the same message.

CONFIGSYSDSN: Unable to create a data source for the 'Oracle in OraClient11g_home'driver:
Could not write to the registry with error code - 2147467259

 Any suggestions?
//Cherie

**Comment by mcanova-usgs** [comment]
Hi Cherie,
Check out these instructions and we'll see if this method works for you.
http://nwis.usgs.gov/IT/INSTRUCT/HOWTO/DB_oracle_odbc.html

Try to set up a User DSN. It is the last bit of instructions at the end of the page.

**Comment by tmills-usgs** [comment]
Cherie, I apologize for the poor documentation on the ODBC setup. To be honest I don't know how to do it myself and got those instructions from my IT folks. I need a better step-by-step there for sure. Thanks for submitting the issue! I will get on it this week

**Comment by cvmiller565** [comment]
Thanks Mike,
I got further but am not able to load the RGtk2 library. I've tried it a
couple times and restarted RStudio but can't get past this point. It looks
like it might be storing the library in the wrong place, but I'm not sure
where to direct it.
Also - I have a 64 bit machine and am running the odbc in 32 bit mode. Just
FYI.
Any suggestions?
//Cherie


[image: Inline image 1]



***---***---***---***---***---***---***---***---***---***---***---***
Cherie V. Miller, Ph.D.
   cvmiller@usgs.gov
   U.S. Geological Survey             443-498-5554 (phone)
   5522 Research Park Drive         443-498-5510 (FAX)
   Baltimore, Md 21228                 443-745-1688 (cell)
                  __~
            __/oo____/
            \--------------/
          ***---***---***----***

**Comment by tmills-usgs** [comment]
Sorry Cherie, the image did not show up. I assume it was a screenshot of the error. Can you email it to me?
tmills@usgs.gov

**Comment by tmills-usgs** [comment]
Add link to better documentation from Mike
